### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by xiaolan610** [msojocs/bilibili-linux#126]
## 报错信息与错误截图：
![image](https://github.com/user-attachments/assets/af08c3d2-c247-497d-9d4c-419f71139fbe)
**一种日志：**
```log
$>bilibili
ell)
14:00:39.864 (AppService)          › Resource permision error Error: EACCES: permission denied, copyfile '/tmp/.org.chromium.Chromium.uA7Jn2' -> '/home/lan/.config/bilibili/resource/.temp/.bili.html'
at copyFileSync (node:fs:2817:3)
at func (node:electron/js2c/asar_bundle:5:2037)
at /usr/lib/bilibili/app.asar/main/app.js:319:720510
at new Promise (<anonymous>)
at a0.startLocalAppServer (/usr/lib/bilibili/app.asar/main/app.js:319:718957)
at a0.initBilibiliApp (/usr/lib/bilibili/app.asar/main/app.js:319:716774)
at new ao (/usr/lib/bilibili/app.asar/main/app.js:319:772058)
at Injector.instantiateClass (/usr/lib/bilibili/app.asar/node_modules/@nestjs/core/injector/injector.js:330:19)
at callback (/usr/lib/bilibili/app.asar/node_modules/@nestjs/core/injector/injector.js:48:41)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:321538) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `electron21 --trace-warnings ...` to show where the warning was created)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
14:00:40.672 (AppService)             › Cp resource to temp...
14:00:40.672 (AppService)             › Cp temp resource error. Error: EACCES: permission denied, mkdir '/home/lan/.config/bilibili/resource/.temp/C:/GitLab-Runner/builds/_-xxdxze/0/bili-utils/bilibili-electron/app/render'
at mkdirSync (node:fs:1349:3)
at /usr/lib/bilibili/app.asar/main/app.js:319:721818
at Array.forEach (<anonymous>)
at /usr/lib/bilibili/app.asar/main/app.js:319:721244
14:00:40.673 (AppService)             › Run resource default...
(node:321538) electron: Failed to load URL: https://bilipc.bilibili.com/index.html with error: ERR_CONNECTION_RESET
```
另一种：
```log
ell)
14:02:46.458 (AppService)          › Resource permision error Error: EACCES: permission denied, copyfile '/tmp/.org.chromium.Chromium.c7W7I4' -> '/home/lan/.config/bilibili/resource/.temp/.bili.html'
at copyFileSync (node:fs:2817:3)
at func (node:electron/js2c/asar_bundle:5:2037)
at /usr/lib/bilibili/app.asar/main/app.js:319:720510
at new Promise (<anonymous>)
at a0.startLocalAppServer (/usr/lib/bilibili/app.asar/main/app.js:319:718957)
at a0.initBilibiliApp (/usr/lib/bilibili/app.asar/main/app.js:319:716774)
at new ao (/usr/lib/bilibili/app.asar/main/app.js:319:772058)
at Injector.instantiateClass (/usr/lib/bilibili/app.asar/node_modules/@nestjs/core/injector/injector.js:330:19)
at callback (/usr/lib/bilibili/app.asar/node_modules/@nestjs/core/injector/injector.js:48:41)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:322015) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `electron21 --trace-warnings ...` to show where the warning was created)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
14:02:47.265 (AppService)             › Cp resource to temp...
14:02:47.266 (AppService)             › Cp temp resource error. Error: EACCES: permission denied, mkdir '/home/lan/.config/bilibili/resource/.temp/C:/GitLab-Runner/builds/_-xxdxze/0/bili-utils/bilibili-electron/app/render'
at mkdirSync (node:fs:1349:3)
at /usr/lib/bilibili/app.asar/main/app.js:319:721818
at Array.forEach (<anonymous>)
at /usr/lib/bilibili/app.asar/main/app.js:319:721244
14:02:47.266 (AppService)             › Run resource default...
[322015:0811/140303.472158:ERROR:cert_verify_proc_builtin.cc(670)] CertVerifyProcBuiltin for bilipc.bilibili.com failed:
----- Certificate i=0 (CN=*.com.host) -----
ERROR: Time is after notAfter


(node:322015) electron: Failed to load URL: https://bilipc.bilibili.com/index.html with error: ERR_CERT_COMMON_NAME_INVALID
```
##系统信息
x64-arch-linux_zen

**Comment by msojocs** [comment]
使用的软件包名称是什么？

**Comment by xiaolan610** [comment]
electron21-bin+bilibili-bin

**Comment by msojocs** [comment]
aur安装？

**Comment by xiaolan610** [comment]
是的

**Comment by xiaolan610** [comment]
我自编译运行结果也一样

**Comment by msojocs** [comment]
那你截图和日志用自己构建的，aur不是我维护的，我不熟。
或者看看AppIamge的情况。

**Comment by xiaolan610** [comment]
同样...
