### ISSUE TITLE
无法安装新版本

### ISSUE THREAD

**Issue by wushuangliu070** [msojocs/bilibili-linux#22]
解密
internal/crypto/cipher.js:172
  const ret = this[kHandle].final();
                            ^

Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (internal/crypto/cipher.js:172:29)
    at Object.<anonymous> (/home/wray/exec/bilibili/bilibili-linux/tools/app-decrypt.js:22:85)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
 失败  command: "$root_dir/tools/app-decrypt.js" "$res_dir/app/main/.biliapp" "$res_dir/app/main/app.orgi.js"
  at /home/wray/exec/bilibili/bilibili-linux/tools/fix-other.sh:25
  at

**Comment by msojocs** [comment]
收到，已验证。

小版本号发生变更：`1.1.3.494` -> `1.1.3.542`

https://github.com/msojocs/bilibili-linux/actions/runs/2433875044

**Comment by msojocs** [comment]
已处理
